"""Render Task 8's acceptance evidence FROM the harness run records.

The document is derived, never authored. A hand-written evidence table is a
figure nothing else has read (D032), and a number that exists only in a session
is not evidence (D034) -- so this reads the JSON the acceptance harness printed
and refuses anything it cannot substantiate.

    py -3.12 tools/render_acceptance_evidence.py `
      --records .artifacts/task8 `
      --out docs/evidence/schema-v2-candidate-acceptance.md

`--check` re-renders and compares instead of writing, so a stale committed
document fails rather than being silently believed.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

#: Every workflow Task 8 must accept, and how many passing runs each needs.
REQUIRED = {
    "EXPORT_DATA": 3,
    "OPEN_FOLDER": 3,
    "OPEN_TERMINAL": 3,
}

#: Intents whose gate asserts UIA provenance rather than completion. Fallback
#: OCR preserves the outcome while the preferred tier is dark, so an
#: outcome-only gate cannot see a tier going dark (D069).
UIA_PROVENANCE_REQUIRED = {"OPEN_FOLDER"}


class EvidenceRefused(Exception):
    """Raised rather than emitting a document that overstates what was run."""


def load_records(directory: pathlib.Path) -> list[dict]:
    records = []
    for path in sorted(directory.glob("*.json")):
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise EvidenceRefused(f"{path.name}: not valid JSON ({exc})") from exc
        # A preparation record explicitly is not acceptance evidence, and says
        # so in its own payload. Take it at its word.
        if record.get("record_kind") != "run":
            raise EvidenceRefused(
                f"{path.name}: record_kind is {record.get('record_kind')!r}, not 'run'"
            )
        if not record.get("is_acceptance_evidence"):
            raise EvidenceRefused(f"{path.name}: not marked as acceptance evidence")
        record["_source"] = path.name
        records.append(record)
    if not records:
        raise EvidenceRefused(f"no run records under {directory}")
    return records


def group(records: list[dict]) -> dict:
    by_intent: dict = {}
    for record in records:
        by_intent.setdefault(record["intent_id"], []).append(record)
    return by_intent


def check(by_intent: dict) -> None:
    """Every refusal Task 8's acceptance policy states, applied to real records."""
    missing = sorted(set(REQUIRED) - set(by_intent))
    if missing:
        raise EvidenceRefused(f"no runs recorded for {missing}")
    unexpected = sorted(set(by_intent) - set(REQUIRED))
    if unexpected:
        raise EvidenceRefused(f"records for unrequired intents: {unexpected}")

    for intent_id, runs in sorted(by_intent.items()):
        passed = [r for r in runs if r["outcome"] == "passed"]
        if len(passed) < REQUIRED[intent_id]:
            failures = [
                f"{r['_source']}={r['outcome']}" for r in runs if r not in passed
            ]
            raise EvidenceRefused(
                f"{intent_id}: {len(passed)} passing of {REQUIRED[intent_id]} "
                f"required ({len(runs)} recorded; {failures or 'none failed'})"
            )
        # One intent, one set of bytes: runs that tested different artifacts
        # cannot be added together into a 3/3.
        digests = {json.dumps(r["digests"], sort_keys=True) for r in runs}
        if len(digests) != 1:
            raise EvidenceRefused(
                f"{intent_id}: runs tested {len(digests)} digest sets"
            )
        identities = {
            json.dumps(r["application_identity"], sort_keys=True) for r in runs
        }
        if len(identities) != 1:
            raise EvidenceRefused(
                f"{intent_id}: runs saw {len(identities)} application identities"
            )
        if intent_id in UIA_PROVENANCE_REQUIRED:
            degraded = [
                r["_source"] for r in passed if not r.get("grounded_by_uia_only")
            ]
            if degraded:
                raise EvidenceRefused(
                    f"{intent_id}: passed on non-UIA grounding in {degraded}; "
                    "this gate asserts provenance, not completion (D069)"
                )


def render(by_intent: dict) -> str:
    lines = [
        "# Schema v2 candidate acceptance",
        "",
        "Generated by `tools/render_acceptance_evidence.py` from the JSON records",
        "the acceptance harness printed. Do not edit by hand: `--check` re-renders",
        "and compares, so an edited table fails rather than being believed.",
        "",
        "Every candidate below remains **quarantined**. Acceptance evidence is",
        "committed before installation and activation, never alongside them (D070).",
        "",
    ]
    for intent_id, runs in sorted(by_intent.items()):
        first = runs[0]
        identity = first["application_identity"]
        lines += [
            f"## {intent_id}",
            "",
            f"- Pack: `{first['pack_id']}`",
            f"- Application identity: `{identity['kind']}` = `{identity['value']}`",
            "- Artifacts tested, by full SHA-256:",
            "",
        ]
        for name, digest in sorted(first["digests"].items()):
            lines.append(f"  - `{name}` -- `{digest}`")
        lines += [
            "",
            "| Run | Outcome | Steps | Grounding | UIA only | Target | Detail |",
            "|---|---|---|---|---|---|---|",
        ]
        for record in runs:
            steps = record["steps"]
            provenance = ", ".join(record["grounding_provenance"]) or "--"
            uia_only = "yes" if record.get("grounded_by_uia_only") else "no"
            target = record["target"]
            lines.append(
                f"| `{record['_source']}` | {record['outcome']} "
                f"| {steps['completed']}/{steps['total']} | {provenance} "
                f"| {uia_only} | `{target['executable']}` -- {target['title']!r} "
                # A failure's own reason, from the record. Without it the table
                # says a run failed and not what it reported, which is the half
                # a reader actually needs.
                f"| {record.get('detail') or '--'} |"
            )
        lines.append("")
        if intent_id in UIA_PROVENANCE_REQUIRED:
            lines += [
                "This gate asserts UIA provenance, not completion. Fallback OCR",
                "preserves the outcome while the preferred tier is dark, so an",
                "outcome-only gate cannot see a tier going dark (D069).",
                "",
            ]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--records", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        by_intent = group(load_records(args.records))
        check(by_intent)
    except EvidenceRefused as exc:
        print(f"refused: {exc}", file=sys.stderr)
        return 2

    rendered = render(by_intent)
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != rendered:
            print(
                f"refused: {args.out} is not what the records render", file=sys.stderr
            )
            return 1
        print(f"{args.out} matches its run records")
        return 0
    args.out.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
